export type ValidationReason =
  | 'DEBTOR_NAME_REQUIRED'
  | 'DEBTOR_ACCOUNT_INVALID'
  | 'TRANSACTION_COUNT_OUT_OF_RANGE'
  | 'CREDITOR_NAME_REQUIRED'
  | 'CREDITOR_ACCOUNT_INVALID'
  | 'AMOUNT_INVALID'
  | 'AMOUNT_BELOW_MINIMUM';
